# Имя рабочего процесса, которое будет отображаться в разделе "Actions"
name: 'Выгрузка звонков с агента ElevenLabs (каждые 30 минут)'

# Триггеры для запуска рабочего процесса
on:
  # 1. Запуск по расписанию (cron-синтаксис)
  schedule:
    # Эта строчка означает "запускать каждые 30 минут"
    # (в 0, 30 минут каждого часа).
    - cron: '*/30 * * * *'
  
  # 2. Ручной запуск
  # Позволяет запускать этот рабочий процесс вручную со страницы "Actions"
  # Это очень удобно для тестирования.
  workflow_dispatch:

# Список задач, которые нужно выполнить
jobs:
  # Имя задачи (может быть любым, например, build, deploy, run-script)
  run-python-script:
    # Указываем, на какой операционной системе будет работать скрипт
    # 'ubuntu-latest' — стандартный и надежный выбор
    runs-on: ubuntu-latest

    # Шаги, которые будут последовательно выполнены
    steps:
      # Шаг 1: Клонирование репозитория
      # Этот шаг загружает ваш код (включая Python-скрипт) на виртуальную машину
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Установка Python
      # Указываем, какую версию Python мы хотим использовать
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      # Шаг 3: Установка зависимостей
      # Устанавливаем все библиотеки, которые требуются вашему скрипту для работы
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests google-api-python-client google-auth-oauthlib google-auth-httplib2

      # Шаг 4: Запуск скрипта
      # Выполняем ваш основной Python-файл
      - name: Run Python Script
        # 'env' блок безопасно передает ваши секреты в переменные окружения,
        # которые скрипт читает с помощью os.getenv()
        env:
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          AGENT_4_ID: ${{ secrets.AGENT_4_ID }}
          AGENT_4_DOC_ID: ${{ secrets.AGENT_4_DOC_ID }}
          AGENT_4_DRIVE_FOLDER_ID: ${{ secrets.AGENT_4_DRIVE_FOLDER_ID }}
          GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        # ОБЯЗАТЕЛЬНО замените 'your_script_name.py' на реальное имя вашего файла!
          run: python agent_4_main.py 
